TH2 1836 license check task
th2-net/th2-estore pull request #101
Opened 2024-05-07 13:16 UTC by Andrei-Shulika

Adding a workflow file to do a license check at every iteration

2024-05-07 14:55 UTC, OptimumCode requested changes

2024-05-07 19:16 UTC, Andrei-Shulika commented on .github/workflows/license_check.yml
> +        wget -q -O check_licenses.sh https://raw.githubusercontent.com/th2-net/.github/th2-1836-json-files-update/license-compliance/check_licenses.sh
agreed. will come back when it is done

2024-05-14 13:10 UTC, Andrei-Shulika commented on .github/workflows/license_check.yml
> +      runsOn: 'ubuntu-22.04'
done

2024-05-15 14:45 UTC, Andrei-Shulika commented on .github/workflows/license_check.yml
> +    runs-on: 'ubuntu-22.04'
fixed

2024-05-15 14:45 UTC, Andrei-Shulika commented on .github/workflows/license_check.yml
> +        wget -q -O check_licenses.sh https://raw.githubusercontent.com/th2-net/.github/th2-1836-json-files-update/license-compliance/check_licenses.sh
done

2024-05-16 07:07 UTC, Nikita-Smirnov-Exactpro requested changes

2024-05-16 07:07 UTC, Nikita-Smirnov-Exactpro commented on .github/workflows/license_check.yml
> +    uses: th2-net/.github/.github/workflows/license_check.yml@main
We must integrate this check into templates in .github repository used in "all" existed components:
- th2-net/.github/.github/workflows/compound-java.yml
- th2-net/.github/.github/workflows/compound-java-dev.yml
- maybe other.

2024-05-16 09:12 UTC, Andrei-Shulika commented on .github/workflows/license_check.yml
> +    uses: th2-net/.github/.github/workflows/license_check.yml@main
As for my understanding, in this case it will apply the check for all components. 
Do we agree to enable this check to all components?

2024-05-16 10:01 UTC, OptimumCode commented on .github/workflows/license_check.yml
> +    uses: th2-net/.github/.github/workflows/license_check.yml@main
I think we are. As a job that can fail (for now at least) so we won't be blocked the job failure

2024-05-16 11:25 UTC, Andrei-Shulika commented on .github/workflows/license_check.yml
> +    uses: th2-net/.github/.github/workflows/license_check.yml@main
Resolved here. Please see the following PR for the main workflows.
https://github.com/th2-net/.github/pull/58#issue-2300095466

2024-05-17 06:33 UTC, Nikita-Smirnov-Exactpro commented on .github/workflows/license_check.yml
> +    uses: th2-net/.github/.github/workflows/license_check.yml@main
Could we close this PR?

2024-05-17 06:33 UTC, Nikita-Smirnov-Exactpro commented
Could we close this PR?

2024-05-17 07:28 UTC, closed without merging

2024-05-17 07:28 UTC, Andrei-Shulika commented
Closed as this merge is not needed anymore. Changes related to the check of license applied into the main branch.