[TH2-5204] External executor
th2-net/th2-estore pull request #104
Opened 2024-06-04 07:13 UTC by lumber1000

2024-06-05 06:45 UTC, Nikita-Smirnov-Exactpro requested changes

2024-06-05 06:45 UTC, Nikita-Smirnov-Exactpro commented on README.md
>    image-version: <image version>
```suggestion
  imageName: ghcr.io/th2-net/th2-estore
  imageVersion: <image version>
```

2024-06-05 06:45 UTC, Nikita-Smirnov-Exactpro commented on README.md
> +The component provides a performance of 100K events per second if the events are packaged in batches of 20 or more events.
Please add information about parameters: body size, event status

2024-06-05 06:45 UTC, Nikita-Smirnov-Exactpro commented on README.md
> +Note: for smaller batches (less than 100 events) higher mqRouter.prefetchCount value should be used (e.g. 1000) to achieve these results.
Could we use prefetch 1000 by default?

2024-06-05 06:45 UTC, Nikita-Smirnov-Exactpro commented on build.gradle
> +    cradleVersion = '5.4.0-TH2-5204-external-executor-9367305817-5697938-SNAPSHOT'
Use release version

2024-06-05 06:45 UTC, Nikita-Smirnov-Exactpro commented on src/main/java/com/exactpro/th2/estore/EventPersistor.java
> +        this.samplerService = Executors.newScheduledThreadPool(Runtime.getRuntime().availableProcessors()); // FIXME: make thread count configurable
Let's implement it. estore can use Runtime.getRuntime().availableProcessors() when the new configuration has value less than 1

2024-06-05 06:45 UTC, Nikita-Smirnov-Exactpro commented on src/main/java/com/exactpro/th2/estore/EventPersistor.java
> +                            },
please reformat

2024-06-05 08:21 UTC, OptimumCode commented on perf_chart.png
note: Can we add a legend? Right not it is impossible to understand what is what on this chart

2024-06-05 08:21 UTC, OptimumCode commented on README.md
> +Processing speed (K events/sec) vs batch size for estore:
note: This text does not mention that the total load was around ~100K event/s. Without that information the char looks a bit strange - we have 100K for 700 events in batch and 20 events in batch. But estore can do more - this is just a load limitation. Also, if we turn the X-axe so it starts from the smaller number of events in batch it would be more representative, I think

2024-06-05 08:34 UTC, lumber1000 commented on README.md
> +Note: for smaller batches (less than 100 events) higher mqRouter.prefetchCount value should be used (e.g. 1000) to achieve these results.
If prefetch 1000 is used, memory limit should be increased. Prefetch 1000 is useless for large batches and takes a lot of memory.

2024-06-05 10:29 UTC, lumber1000 commented on src/main/java/com/exactpro/th2/estore/EventPersistor.java
> +        this.samplerService = Executors.newScheduledThreadPool(Runtime.getRuntime().availableProcessors()); // FIXME: make thread count configurable
I suppose we should treat values less than 1 as config error and use availableProcessors() only if value is not specified (null).

2024-06-10 06:54 UTC, Nikita-Smirnov-Exactpro requested changes

2024-06-10 06:54 UTC, Nikita-Smirnov-Exactpro commented on perftest/perftest.md
> +## Computation resources
Could you please add heap graphic for estore.

2024-06-10 06:54 UTC, Nikita-Smirnov-Exactpro commented on perftest/perftest.md
> ++ **Docker image**: ghcr.io/th2-net/th2-estore:5.7.0-external-executor-9384699236-c134f80
Please write dev release version instead special build

2024-06-10 06:54 UTC, Nikita-Smirnov-Exactpro commented on perftest/perftest.md
> ++ **Cradle compression type**: LZ4
Could you please add the whole estore CR and add link to special commit of schema (set git tag before that to avoid losing commit)

2024-06-10 06:54 UTC, Nikita-Smirnov-Exactpro commented on perftest/perftest.md
> +![RabbitMQ RAM](rabbitmq_ram.png)
Could you please explain and / or add other screenshots described reason of spike in the perftest/rabbitmq_ram.png graphic

2024-06-11 11:08 UTC, lumber1000 commented on perftest/perftest.md
> +![RabbitMQ RAM](rabbitmq_ram.png)
I've rerun test and updated this chart. There is no such huge spike on it. I suppose this is a normal ram consumption fluctuation.

2024-06-12 06:08 UTC, Nikita-Smirnov-Exactpro reviewed
Could you please bump maintenance version and add readme.
Sorry it isn't actual

2024-06-12 06:08 UTC, Nikita-Smirnov-Exactpro commented on src/main/java/com/exactpro/th2/estore/ProtoUtil.java
> +            throw new IllegalArgumentException("No unique identifier specified for event: " + protoEventID);
could you please use JsonFormatter for protoEventID

2024-06-12 06:11 UTC, Nikita-Smirnov-Exactpro commented on README.md
> +Note: for smaller batches (less than 100 events) higher mqRouter.prefetchCount value should be used (e.g. 1000) to achieve these results.
OK, I think we should use prefetch count count more than 100 otherwise estore will not be flexible for processing different events

2024-06-12 06:14 UTC, Nikita-Smirnov-Exactpro commented on src/main/java/com/exactpro/th2/estore/EventPersistor.java
> +        this.samplerService = Executors.newScheduledThreadPool(Runtime.getRuntime().availableProcessors()); // FIXME: make thread count configurable
OK

2024-06-12 06:18 UTC, Nikita-Smirnov-Exactpro submitted a review, later dismissed

2024-06-12 08:13 UTC, OptimumCode commented on perftest/perftest.md
> +https://gitlab.exactpro.com/vivarium/th2/th2-internal-instances/th2-perf-schemas/-/commit/0b8dc314356aaa12816f0165408137ac24584781
issue: Please, remove link to the internal resource

2024-06-12 08:13 UTC, OptimumCode commented on perftest/perftest.md
> +        -Djava.rmi.server.hostname=127.0.0.1
note: I think we should remove all parameters that were used for debugging and profiling

2024-06-12 08:28 UTC, lumber1000 commented on perftest/perftest.md
> +https://gitlab.exactpro.com/vivarium/th2/th2-internal-instances/th2-perf-schemas/-/commit/0b8dc314356aaa12816f0165408137ac24584781
@Nikita-Smirnov-Exactpro should we have this link here? (I added it by your request).

2024-06-12 09:58 UTC, OptimumCode commented on src/main/java/com/exactpro/th2/estore/ProtoUtil.java
> +                eventString = JsonFormat.printer().print(protoEventID);
note: there is `toJson` method in common lib (`MessageUtils.toJson` for Java) you can use here. By default, JsonFormat will "pretty-print" the object. We don't need all those indentations in logs

2024-06-25 12:57 UTC, Nikita-Smirnov-Exactpro commented on perftest/perftest.md
> +https://gitlab.exactpro.com/vivarium/th2/th2-internal-instances/th2-perf-schemas/-/commit/0b8dc314356aaa12816f0165408137ac24584781
We shouldn't add link to internal resources into open source.
I will add CRs for these cases

2024-06-30 08:20 UTC, OptimumCode approved these changes
chore: cradle version must be updated to a release version

2024-07-03 09:38 UTC, OptimumCode approved these changes

2024-07-03 12:16 UTC, merged