[th2-2689] adaptation to book/page cradleapi
th2-net/th2-estore pull request #24
Opened 2021-11-19 11:46 UTC by andreydrobynin

2021-11-19 11:47 UTC, andreydrobynin commented
Related to https://github.com/th2-net/th2-common-j/pull/145, https://github.com/th2-net/th2-store-common/pull/12, https://github.com/th2-net/th2-mstore/pull/22

2021-11-23 15:42 UTC, Nikita-Smirnov-Exactpro requested changes

2021-11-23 15:42 UTC, Nikita-Smirnov-Exactpro commented on src/main/java/com/exactpro/th2/estore/ReportRabbitMQEventStoreService.java
> +        TestEventBatchToStore cradleBatch = toCradleBatch(protoBatch, "", "", protoBatch.getEvents(0).getStartTimestamp());
Events in a batch can be placed in the timestamp increasing order, please find minimal from all events in batch.

2021-11-23 15:42 UTC, Nikita-Smirnov-Exactpro commented on src/main/java/com/exactpro/th2/estore/ReportRabbitMQEventStoreService.java
> +        TestEventBatchToStore cradleBatch = toCradleBatch(protoBatch, "", "", protoBatch.getEvents(0).getStartTimestamp());
Let's add the scope field into the Protobuf EventID message and use it to build Cradle entities

2021-11-24 19:07 UTC, andreydrobynin commented on src/main/java/com/exactpro/th2/estore/ReportRabbitMQEventStoreService.java
> +        TestEventBatchToStore cradleBatch = toCradleBatch(protoBatch, "", "", protoBatch.getEvents(0).getStartTimestamp());
done

2021-11-26 08:35 UTC, Nikita-Smirnov-Exactpro requested changes

2021-11-26 08:35 UTC, Nikita-Smirnov-Exactpro commented on src/main/java/com/exactpro/th2/estore/ReportRabbitMQEventStoreService.java
> +                if (events.size() == 1) {
Size checking is redundant and we can use the code from else block

2021-11-26 08:35 UTC, Nikita-Smirnov-Exactpro commented on src/main/java/com/exactpro/th2/estore/ReportRabbitMQEventStoreService.java
> +        comparator.thenComparing(event -> event.getStartTimestamp().getNanos());
```suggestion
        Comparator<Event> comparator = Comparator.comparing(event -> event.getStartTimestamp().getSeconds())
                                                                          .thenComparing(event -> event.getStartTimestamp().getNanos());
```

2021-11-26 08:35 UTC, Nikita-Smirnov-Exactpro commented on src/main/java/com/exactpro/th2/estore/ReportRabbitMQEventStoreService.java
> +        comparator.thenComparing(event -> event.getStartTimestamp().getNanos());
Please make a test for this case

2021-11-26 08:41 UTC, andreydrobynin commented on src/main/java/com/exactpro/th2/estore/ReportRabbitMQEventStoreService.java
> +                if (events.size() == 1) {
I didn't change this logic, I just moved duplicated size check in case `!eventBatch.hasParentEventId()`.
In case `events.size() == 1` we call `storeEvent(events.get(0))`.
In else case we call
```
for (Event event : events) {
    storeEvent(event);
}
```

2021-11-26 09:38 UTC, andreydrobynin commented on src/main/java/com/exactpro/th2/estore/ReportRabbitMQEventStoreService.java
> +        comparator.thenComparing(event -> event.getStartTimestamp().getNanos());
`thenComparing` requires explicit `<Event>`, please see:
```
Comparator<Event> comparator = Comparator
        .<Event>comparingLong(event -> event.getStartTimestamp().getSeconds())
        .thenComparingInt(event -> event.getStartTimestamp().getNanos());
```
Also as I see method `storeEventBatch` called from 2 tests: `testEventsBatchDelivery` and `testEventsBatchDeliveryWithMessages`. 
They both failed if I change e.g. comparator from min to max.

2021-11-28 11:05 UTC, Nikita-Smirnov-Exactpro approved these changes

2021-11-28 11:05 UTC, Nikita-Smirnov-Exactpro commented on src/main/java/com/exactpro/th2/estore/ProtoUtil.java
> +    public static Comparator<Event> EVENT_MIN_START_TIMESTAMP_COMPARATOR = Comparator
```suggestion
    public static Comparator<Event> EVENT_START_TIMESTAMP_COMPARATOR = Comparator
```

2021-11-29 10:52 UTC, andreydrobynin commented on src/main/java/com/exactpro/th2/estore/ProtoUtil.java
> +    public static Comparator<Event> EVENT_MIN_START_TIMESTAMP_COMPARATOR = Comparator
done

2021-11-29 12:43 UTC, merged