Th2 1211
th2-net/th2-estore pull request #8
Opened 2020-12-22 08:07 UTC by Nikita-Smirnov-Exactpro

2020-12-22 08:40 UTC, ivandruzhinin commented on README.md
> +This list of supported features which provided libraries.
Did you mean "This is a list of supported features which this library provides" or "This is a list of supported features provided by libraries"? I guess it is the latter one

2020-12-22 08:58 UTC, jean-michel-perli-sonsin commented on README.md
> +1. CradleMaxEventBatchSize - the option defines the maximum of the event batch size in bytes.
CradleMaxEventBatchSize - **this** option defines the **maximum event batch** size in bytes.

2020-12-22 08:58 UTC, jean-michel-perli-sonsin commented on README.md
> +Please see more details about the future via [link](https://github.com/th2-net/th2-common-j#configuration-formats)
Please see more details about **this feature** via [link](https://github.com/th2-net/th2-common-j#configuration-formats)

2020-12-22 09:01 UTC, jean-michel-perli-sonsin requested changes
I reviewed some errors in two phrases, please take a look and correct them. Thanks.

2020-12-23 10:22 UTC, OptimumOpium submitted a review, later dismissed
Looks fine to me. But have to update the store-common project as well. Otherwise, people will continue to create events in  the old way

2021-01-15 13:19 UTC, OptimumOpium approved these changes

2021-01-15 14:39 UTC, merged